import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/providers/toast-provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "800", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
